apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: ecomerrce2-email-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ecom_email"
