apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ecom
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - name: frontend
          image: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/ecomerrce2-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:

            - name: VITE_PRODUCT_SERVICE_URL
              value: "/api/product"
            - name: VITE_SEARCH_SERVICE_URL
              value: "/api/search"
            - name: VITE_PAYMENT_SERVICE_URL
              value: "/api/payment"
            - name: VITE_EMAIL_SERVICE_URL
              value: "/api/email"
            - name: VITE_CART_SERVICE_URL
              value: "/api/cart"
