apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ecomerrce2-payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ecom_payment"
