apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ecom
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - name: email-service
          image: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/ecomerrce2-email-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: DATABASE_URL
