apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: 183631346881.dkr.ecr.us-east-1.amazonaws.com/ecomerrce2-cart-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ecom_cart"
