apiVersion: v1
kind: Service
metadata:
  namespace: ecom
  name: cart-service
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
